# Lab 05 - TF-IDF

In [1]:
#Release: 1.2107.2401

You will learn how to:
1. Calculate TF-IDF using TfidfVectorizer
2. View data in pandas DataFrame

<br>
 
***If you use Google Colab, install sastrawi package***

In [2]:
!pip install sastrawi

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
     |████████████████████████████████| 209 kB 4.1 MB/s
Installing collected packages: sastrawi
Successfully installed sastrawi-1.0.1

<br>

#### Import required library

In [3]:
import nltk
import re
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from sklearn.feature_extraction.text import TfidfVectorizer

<br>
 
***If you use Google Colab, download stopwords dan punkt package***

In [4]:
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [5]:
stopwords = nltk.corpus.stopwords.words('indonesian')

In [6]:
len(stopwords)

758

In [7]:
stopwords

['ada',
 'adalah',
 'adanya',
 'adapun',
 'agak',
 'agaknya',
 'agar',
 'akan',
 'akankah',
 'akhir',
 'akhiri',
 'akhirnya',
 'aku',
 'akulah',
 'amat',
 'amatlah',
 'anda',
 'andalah',
 'antar',
 'antara',
 'antaranya',
 'apa',
 'apaan',
 'apabila',
 'apakah',
 'apalagi',
 'apatah',
 'artinya',
 'asal',
 'asalkan',
 'atas',
 'atau',
 'ataukah',
 'ataupun',
 'awal',
 'awalnya',
 'bagai',
 'bagaikan',
 'bagaimana',
 'bagaimanakah',
 'bagaimanapun',
 'bagi',
 'bagian',
 'bahkan',
 'bahwa',
 'bahwasanya',
 'baik',
 'bakal',
 'bakalan',
 'balik',
 'banyak',
 'bapak',
 'baru',
 'bawah',
 'beberapa',
 'begini',
 'beginian',
 'beginikah',
 'beginilah',
 'begitu',
 'begitukah',
 'begitulah',
 'begitupun',
 'bekerja',
 'belakang',
 'belakangan',
 'belum',
 'belumlah',
 'benar',
 'benarkah',
 'benarlah',
 'berada',
 'berakhir',
 'berakhirlah',
 'berakhirnya',
 'berapa',
 'berapakah',
 'berapalah',
 'berapapun',
 'berarti',
 'berawal',
 'berbagai',
 'berdatangan',
 'beri',
 'berikan',
 'berikut',
 'berikutnya',
 'berjumlah',
 'berkali-kali',
 'berkata',
 'berkehendak',
 'berkeinginan',
 'berkenaan',
 'berlainan',
 'berlalu',
 'berlangsung',
 'berlebihan',
 'bermacam',
 'bermacam-macam',
 'bermaksud',
 'bermula',
 'bersama',
 'bersama-sama',
 'bersiap',
 'bersiap-siap',
 'bertanya',
 'bertanya-tanya',
 'berturut',
 'berturut-turut',
 'bertutur',
 'berujar',
 'berupa',
 'besar',
 'betul',
 'betulkah',
 'biasa',
 'biasanya',
 'bila',
 'bilakah',
 'bisa',
 'bisakah',
 'boleh',
 'bolehkah',
 'bolehlah',
 'buat',
 'bukan',
 'bukankah',
 'bukanlah',
 'bukannya',
 'bulan',
 'bung',
 'cara',
 'caranya',
 'cukup',
 'cukupkah',
 'cukuplah',
 'cuma',
 'dahulu',
 'dalam',
 'dan',
 'dapat',
 'dari',
 'daripada',
 'datang',
 'dekat',
 'demi',
 'demikian',
 'demikianlah',
 'dengan',
 'depan',
 'di',
 'dia',
 'diakhiri',
 'diakhirinya',
 'dialah',
 'diantara',
 'diantaranya',
 'diberi',
 'diberikan',
 'diberikannya',
 'dibuat',
 'dibuatnya',
 'didapat',
 'didatangkan',
 'digunakan',
 'diibaratkan',
 'diibaratkannya',
 'diingat',
 'diingatkan',
 'diinginkan',
 'dijawab',
 'dijelaskan',
 'dijelaskannya',
 'dikarenakan',
 'dikatakan',
 'dikatakannya',
 'dikerjakan',
 'diketahui',
 'diketahuinya',
 'dikira',
 'dilakukan',
 'dilalui',
 'dilihat',
 'dimaksud',
 'dimaksudkan',
 'dimaksudkannya',
 'dimaksudnya',
 'diminta',
 'dimintai',
 'dimisalkan',
 'dimulai',
 'dimulailah',
 'dimulainya',
 'dimungkinkan',
 'dini',
 'dipastikan',
 'diperbuat',
 'diperbuatnya',
 'dipergunakan',
 'diperkirakan',
 'diperlihatkan',
 'diperlukan',
 'diperlukannya',
 'dipersoalkan',
 'dipertanyakan',
 'dipunyai',
 'diri',
 'dirinya',
 'disampaikan',
 'disebut',
 'disebutkan',
 'disebutkannya',
 'disini',
 'disinilah',
 'ditambahkan',
 'ditandaskan',
 'ditanya',
 'ditanyai',
 'ditanyakan',
 'ditegaskan',
 'ditujukan',
 'ditunjuk',
 'ditunjuki',
 'ditunjukkan',
 'ditunjukkannya',
 'ditunjuknya',
 'dituturkan',
 'dituturkannya',
 'diucapkan',
 'diucapkannya',
 'diungkapkan',
 'dong',
 'dua',
 'dulu',
 'empat',
 'enggak',
 'enggaknya',
 'entah',
 'entahlah',
 'guna',
 'gunakan',
 'hal',
 'hampir',
 'hanya',
 'hanyalah',
 'hari',
 'harus',
 'haruslah',
 'harusnya',
 'hendak',
 'hendaklah',
 'hendaknya',
 'hingga',
 'ia',
 'ialah',
 'ibarat',
 'ibaratkan',
 'ibaratnya',
 'ibu',
 'ikut',
 'ingat',
 'ingat-ingat',
 'ingin',
 'inginkah',
 'inginkan',
 'ini',
 'inikah',
 'inilah',
 'itu',
 'itukah',
 'itulah',
 'jadi',
 'jadilah',
 'jadinya',
 'jangan',
 'jangankan',
 'janganlah',
 'jauh',
 'jawab',
 'jawaban',
 'jawabnya',
 'jelas',
 'jelaskan',
 'jelaslah',
 'jelasnya',
 'jika',
 'jikalau',
 'juga',
 'jumlah',
 'jumlahnya',
 'justru',
 'kala',
 'kalau',
 'kalaulah',
 'kalaupun',
 'kalian',
 'kami',
 'kamilah',
 'kamu',
 'kamulah',
 'kan',
 'kapan',
 'kapankah',
 'kapanpun',
 'karena',
 'karenanya',
 'kasus',
 'kata',
 'katakan',
 'katakanlah',
 'katanya',
 'ke',
 'keadaan',
 'kebetulan',
 'kecil',
 'kedua',
 'keduanya',
 'keinginan',
 'kelamaan',
 'kelihatan',
 'kelihatannya',
 'kelima',
 'keluar',
 'kembali',
 'kemudian',
 'kemungkinan',
 'kemungkinannya',
 'kenapa',
 'kepada',
 'kepadanya',
 'kesampaian',
 'keseluruhan',
 'keseluruhannya',
 'keterlaluan',
 'ketika',
 'khususnya',
 'kini',
 'kinilah',
 'kira',
 'kira-kira',
 'kiranya',
 'kita',
 'kitalah',
 'kok',
 'kurang',
 'lagi',
 'lagian',
 'lah',
 'lain',
 'lainnya',
 'lalu',
 'lama',
 'lamanya',
 'lanjut',
 'lanjutnya',
 'lebih',
 'lewat',
 'lima',
 'luar',
 'macam',
 'maka',
 'makanya',
 'makin',
 'malah',
 'malahan',
 'mampu',
 'mampukah',
 'mana',
 'manakala',
 'manalagi',
 'masa',
 'masalah',
 'masalahnya',
 'masih',
 'masihkah',
 'masing',
 'masing-masing',
 'mau',
 'maupun',
 'melainkan',
 'melakukan',
 'melalui',
 'melihat',
 'melihatnya',
 'memang',
 'memastikan',
 'memberi',
 'memberikan',
 'membuat',
 'memerlukan',
 'memihak',
 'meminta',
 'memintakan',
 'memisalkan',
 'memperbuat',
 'mempergunakan',
 'memperkirakan',
 'memperlihatkan',
 'mempersiapkan',
 'mempersoalkan',
 'mempertanyakan',
 'mempunyai',
 'memulai',
 'memungkinkan',
 'menaiki',
 'menambahkan',
 'menandaskan',
 'menanti',
 'menanti-nanti',
 'menantikan',
 'menanya',
 'menanyai',
 'menanyakan',
 'mendapat',
 'mendapatkan',
 'mendatang',
 'mendatangi',
 'mendatangkan',
 'menegaskan',
 'mengakhiri',
 'mengapa',
 'mengatakan',
 'mengatakannya',
 'mengenai',
 'mengerjakan',
 'mengetahui',
 'menggunakan',
 'menghendaki',
 'mengibaratkan',
 'mengibaratkannya',
 'mengingat',
 'mengingatkan',
 'menginginkan',
 'mengira',
 'mengucapkan',
 'mengucapkannya',
 'mengungkapkan',
 'menjadi',
 'menjawab',
 'menjelaskan',
 'menuju',
 'menunjuk',
 'menunjuki',
 'menunjukkan',
 'menunjuknya',
 'menurut',
 'menuturkan',
 'menyampaikan',
 'menyangkut',
 'menyatakan',
 'menyebutkan',
 'menyeluruh',
 'menyiapkan',
 'merasa',
 'mereka',
 'merekalah',
 'merupakan',
 'meski',
 'meskipun',
 'meyakini',
 'meyakinkan',
 'minta',
 'mirip',
 'misal',
 'misalkan',
 'misalnya',
 'mula',
 'mulai',
 'mulailah',
 'mulanya',
 'mungkin',
 'mungkinkah',
 'nah',
 'naik',
 'namun',
 'nanti',
 'nantinya',
 'nyaris',
 'nyatanya',
 'oleh',
 'olehnya',
 'pada',
 'padahal',
 'padanya',
 'pak',
 'paling',
 'panjang',
 'pantas',
 'para',
 'pasti',
 'pastilah',
 'penting',
 'pentingnya',
 'per',
 'percuma',
 'perlu',
 'perlukah',
 'perlunya',
 'pernah',
 'persoalan',
 'pertama',
 'pertama-tama',
 'pertanyaan',
 'pertanyakan',
 'pihak',
 'pihaknya',
 'pukul',
 'pula',
 'pun',
 'punya',
 'rasa',
 'rasanya',
 'rata',
 'rupanya',
 'saat',
 'saatnya',
 'saja',
 'sajalah',
 'saling',
 'sama',
 'sama-sama',
 'sambil',
 'sampai',
 'sampai-sampai',
 'sampaikan',
 'sana',
 'sangat',
 'sangatlah',
 'satu',
 'saya',
 'sayalah',
 'se',
 'sebab',
 'sebabnya',
 'sebagai',
 'sebagaimana',
 'sebagainya',
 'sebagian',
 'sebaik',
 'sebaik-baiknya',
 'sebaiknya',
 'sebaliknya',
 'sebanyak',
 'sebegini',
 'sebegitu',
 'sebelum',
 'sebelumnya',
 'sebenarnya',
 'seberapa',
 'sebesar',
 'sebetulnya',
 'sebisanya',
 'sebuah',
 'sebut',
 'sebutlah',
 'sebutnya',
 'secara',
 'secukupnya',
 'sedang',
 'sedangkan',
 'sedemikian',
 'sedikit',
 'sedikitnya',
 'seenaknya',
 'segala',
 'segalanya',
 'segera',
 'seharusnya',
 'sehingga',
 'seingat',
 'sejak',
 'sejauh',
 'sejenak',
 'sejumlah',
 'sekadar',
 'sekadarnya',
 'sekali',
 'sekali-kali',
 'sekalian',
 'sekaligus',
 'sekalipun',
 'sekarang',
 'sekarang',
 'sekecil',
 'seketika',
 'sekiranya',
 'sekitar',
 'sekitarnya',
 'sekurang-kurangnya',
 'sekurangnya',
 'sela',
 'selain',
 'selaku',
 'selalu',
 'selama',
 'selama-lamanya',
 'selamanya',
 'selanjutnya',
 'seluruh',
 'seluruhnya',
 'semacam',
 'semakin',
 'semampu',
 'semampunya',
 'semasa',
 'semasih',
 'semata',
 'semata-mata',
 'semaunya',
 'sementara',
 'semisal',
 'semisalnya',
 'sempat',
 'semua',
 'semuanya',
 'semula',
 'sendiri',
 'sendirian',
 'sendirinya',
 'seolah',
 'seolah-olah',
 'seorang',
 'sepanjang',
 'sepantasnya',
 'sepantasnyalah',
 'seperlunya',
 'seperti',
 'sepertinya',
 'sepihak',
 'sering',
 'seringnya',
 'serta',
 'serupa',
 'sesaat',
 'sesama',
 'sesampai',
 'sesegera',
 'sesekali',
 'seseorang',
 'sesuatu',
 'sesuatunya',
 'sesudah',
 'sesudahnya',
 'setelah',
 'setempat',
 'setengah',
 'seterusnya',
 'setiap',
 'setiba',
 'setibanya',
 'setidak-tidaknya',
 'setidaknya',
 'setinggi',
 'seusai',
 'sewaktu',
 'siap',
 'siapa',
 'siapakah',
 'siapapun',
 'sini',
 'sinilah',
 'soal',
 'soalnya',
 'suatu',
 'sudah',
 'sudahkah',
 'sudahlah',
 'supaya',
 'tadi',
 'tadinya',
 'tahu',
 'tahun',
 'tak',
 'tambah',
 'tambahnya',
 'tampak',
 'tampaknya',
 'tandas',
 'tandasnya',
 'tanpa',
 'tanya',
 'tanyakan',
 'tanyanya',
 'tapi',
 'tegas',
 'tegasnya',
 'telah',
 'tempat',
 'tengah',
 'tentang',
 'tentu',
 'tentulah',
 'tentunya',
 'tepat',
 'terakhir',
 'terasa',
 'terbanyak',
 'terdahulu',
 'terdapat',
 'terdiri',
 'terhadap',
 'terhadapnya',
 'teringat',
 'teringat-ingat',
 'terjadi',
 'terjadilah',
 'terjadinya',
 'terkira',
 'terlalu',
 'terlebih',
 'terlihat',
 'termasuk',
 'ternyata',
 'tersampaikan',
 'tersebut',
 'tersebutlah',
 'tertentu',
 'tertuju',
 'terus',
 'terutama',
 'tetap',
 'tetapi',
 'tiap',
 'tiba',
 'tiba-tiba',
 'tidak',
 'tidakkah',
 'tidaklah',
 'tiga',
 'tinggi',
 'toh',
 'tunjuk',
 'turut',
 'tutur',
 'tuturnya',
 'ucap',
 'ucapnya',
 'ujar',
 'ujarnya',
 'umum',
 'umumnya',
 'ungkap',
 'ungkapnya',
 'untuk',
 'usah',
 'usai',
 'waduh',
 'wah',
 'wahai',
 'waktu',
 'waktunya',
 'walau',
 'walaupun',
 'wong',
 'yaitu',
 'yakin',
 'yakni',
 'yang']

<br>

#### Preprocessing function from previous labs

In [8]:
def tokenize_clean(text):
    
    #tokenisasi
    tokens = [word.lower() for sent in nltk.sent_tokenize(text) for word
        in nltk.word_tokenize(sent)]
    
    #clean token from numeric and other character like puntuation
    filtered_tokens = []
    for token in tokens:
        if re.search('[a-zA-Z]', token):
            filtered_tokens.append(token)
            
    return filtered_tokens

In [9]:
def remove_stopwords(tokenized_text):
    
    cleaned_token = []
    for token in tokenized_text:
        if token not in stopwords:
            cleaned_token.append(token)
            
    return cleaned_token

In [10]:
def stemming_text(tokenized_text):
    
    #stem using Sastrawi StemmerFactory 
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()

    stems = []
    for token in tokenized_text:
        stems.append(stemmer.stem(token))

    return stems

In [11]:
def text_preprocessing(text):
    
    prep01 = tokenize_clean(text)
    prep02 = remove_stopwords(prep01)
    prep03 = stemming_text(prep02)
    
    return prep03

<br>

## Small Dataset

<br>

### Step 01 - Create dataset

In [12]:
dataset = [
     'kucing kucing kucing hitam putih belang',
     'tikus belang',
     'tikus hitam',
     'tikus tikus tikus'
]

In [13]:
len(dataset)

4

In [14]:
dataset[2]

'tikus hitam'

### Step 02 - Compute TF-IDF

In [15]:
#perform tf-idf vectorization
vectorizer = TfidfVectorizer(use_idf=True)
result_tfidf = vectorizer.fit_transform(dataset)

### Step 03 - View Result

Get List of Words

In [16]:
print(vectorizer.get_feature_names())

['belang', 'hitam', 'kucing', 'putih', 'tikus']

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [17]:
print(vectorizer.vocabulary_)

{'kucing': 2, 'hitam': 1, 'putih': 3, 'belang': 0, 'tikus': 4}

View TF-IDF Result

In [18]:
print(result_tfidf.shape)

(4, 5)

In [19]:
type(result_tfidf)

scipy.sparse.csr.csr_matrix

In [20]:
print(result_tfidf.toarray())

[[0.23513012 0.23513012 0.89469821 0.29823274 0.        ]
 [0.77722116 0.         0.         0.         0.62922751]
 [0.         0.77722116 0.         0.         0.62922751]
 [0.         0.         0.         0.         1.        ]]

View First Sentence

In [21]:
dataset[0]

'kucing kucing kucing hitam putih belang'

In [22]:
print(result_tfidf[0])

  (0, 0)	0.2351301157996824
  (0, 3)	0.2982327375202219
  (0, 1)	0.2351301157996824
  (0, 2)	0.8946982125606657

In [23]:
print(result_tfidf[0].toarray())

[[0.23513012 0.23513012 0.89469821 0.29823274 0.        ]]

View Second Sentence

In [24]:
print(result_tfidf[1])

  (0, 4)	0.6292275146695526
  (0, 0)	0.7772211620785797

In [25]:
print(result_tfidf[1].toarray())

[[0.77722116 0.         0.         0.         0.62922751]]

In [26]:
dataset[1]

'tikus belang'

In [27]:
vectorizer.get_feature_names()

['belang', 'hitam', 'kucing', 'putih', 'tikus']

In [28]:
import pandas as pd
df = pd.DataFrame(result_tfidf[1].T.todense(), index=vectorizer.get_feature_names(), columns=["TF-IDF"])
df.sort_values(by=['TF-IDF'])

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

          TF-IDF
hitam   0.000000
kucing  0.000000
putih   0.000000
tikus   0.629228
belang  0.777221

<br>

View IDF

In [29]:
# print idf values
df_idf = pd.DataFrame(vectorizer.idf_, index=vectorizer.get_feature_names(),columns=["idf"])
 
# sort ascending
df_idf.sort_values(by=['idf'])

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

             idf
tikus   1.223144
belang  1.510826
hitam   1.510826
kucing  1.916291
putih   1.916291

<br>

### Step 04 - Compute TF-IDF with new sentence

In [30]:
new_text = 'kambing hitam'
result_tfidf = vectorizer.transform([new_text])

feature_names = vectorizer.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [31]:
feature_names

['belang', 'hitam', 'kucing', 'putih', 'tikus']

In [32]:
result_tfidf.toarray()

array([[0., 1., 0., 0., 0.]])

<br>

## Bigger Dataset

### Step 01 - Create dataset

In [33]:
files = []
files.append("Sekelompok ibu dan kaum perempuan duduk beralaskan rumput lapangan sambil fokus menganyam bambu yang ia genggam ditangan.")
files.append("Sebagian besar masyarakat rupanya tak mau melewatkan waktu begitu  saja untuk meratapi erupsi.")
files.append("Lombok memang memiliki sejuta pesona yang mampu menyedot perhatian orang untuk datang berwisata.")
files.append("Perempuan yang bergelut di dunia kerelawanan akan belajar caranya bertanggung jawab bagi sendiri dan orang lain.")
files.append("Kami berkoordinasi dan melapor pada posko relawan, kami berkomitmen  siap membantu dengan siaga 24 jam")

### Step 02 - Corpus preparation

In [34]:
token_dict = {}
i = 0
for t in files:
    filename = "file" + str(i)
    token_dict[filename] = t
    i = i + 1

token_dict

{'file0': 'Sekelompok ibu dan kaum perempuan duduk beralaskan rumput lapangan sambil fokus menganyam bambu yang ia genggam ditangan.',
 'file1': 'Sebagian besar masyarakat rupanya tak mau melewatkan waktu begitu  saja untuk meratapi erupsi.',
 'file2': 'Lombok memang memiliki sejuta pesona yang mampu menyedot perhatian orang untuk datang berwisata.',
 'file3': 'Perempuan yang bergelut di dunia kerelawanan akan belajar caranya bertanggung jawab bagi sendiri dan orang lain.',
 'file4': 'Kami berkoordinasi dan melapor pada posko relawan, kami berkomitmen  siap membantu dengan siaga 24 jam'}

In [35]:
token_dict.values()

dict_values(['Sekelompok ibu dan kaum perempuan duduk beralaskan rumput lapangan sambil fokus menganyam bambu yang ia genggam ditangan.', 'Sebagian besar masyarakat rupanya tak mau melewatkan waktu begitu  saja untuk meratapi erupsi.', 'Lombok memang memiliki sejuta pesona yang mampu menyedot perhatian orang untuk datang berwisata.', 'Perempuan yang bergelut di dunia kerelawanan akan belajar caranya bertanggung jawab bagi sendiri dan orang lain.', 'Kami berkoordinasi dan melapor pada posko relawan, kami berkomitmen  siap membantu dengan siaga 24 jam'])

In [36]:
token_dict['file0']

'Sekelompok ibu dan kaum perempuan duduk beralaskan rumput lapangan sambil fokus menganyam bambu yang ia genggam ditangan.'

### Step 03 - Compute TF-IDF

In [37]:
#perform tf-idf vectorization
tfidf = TfidfVectorizer(max_df=0.8,             # terms with document frequency value > 0.8 will be removed
                        min_df=0.2,             # terms with document frequency value < 0.2 will be removed
                        max_features=200000,    # create maximum 200.000 vocabulary that only consider the top max_features ordered by term frequency across the corpus.
                        stop_words = stopwords, # stopwords list
                        use_idf=True,           # enable inverse-document-frequency reweighting
                        tokenizer=text_preprocessing, # override the string tokenization step by using text_prepocessing function 
                        ngram_range=(1,3))      # ngram range 1 - 3 


tfs = tfidf.fit_transform(token_dict.values())

For detail TfidfVectorizer documentation visit: https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html

### Step 04 - View Result

Let's check the shape. We should have 5 rows (5 docs) and 96 columns (96 unique words):

In [38]:
tfs.shape

(5, 96)

<br>

Inspect the first document vector

In [39]:
print(tfs[0])

  (0, 11)	0.17500574860015006
  (0, 8)	0.17500574860015006
  (0, 24)	0.17500574860015006
  (0, 48)	0.17500574860015006
  (0, 86)	0.17500574860015006
  (0, 5)	0.17500574860015006
  (0, 17)	0.17500574860015006
  (0, 65)	0.17500574860015006
  (0, 36)	0.17500574860015006
  (0, 39)	0.17500574860015006
  (0, 29)	0.17500574860015006
  (0, 10)	0.17500574860015006
  (0, 7)	0.17500574860015006
  (0, 23)	0.17500574860015006
  (0, 47)	0.17500574860015006
  (0, 85)	0.17500574860015006
  (0, 4)	0.17500574860015006
  (0, 16)	0.17500574860015006
  (0, 64)	0.17500574860015006
  (0, 35)	0.17500574860015006
  (0, 38)	0.17500574860015006
  (0, 92)	0.17500574860015006
  (0, 28)	0.17500574860015006
  (0, 9)	0.17500574860015006
  (0, 6)	0.17500574860015006
  (0, 22)	0.17500574860015006
  (0, 46)	0.17500574860015006
  (0, 84)	0.17500574860015006
  (0, 3)	0.17500574860015006
  (0, 15)	0.17500574860015006
  (0, 63)	0.1411935360448027
  (0, 34)	0.17500574860015006
  (0, 37)	0.17500574860015006

View the list of feature

In [40]:
feature_names = tfidf.get_feature_names()

In [41]:
print(len(feature_names))

96

In [42]:
print(feature_names)

['ajar', 'ajar tanggung', 'ajar tanggung orang', 'alas', 'alas rumput', 'alas rumput lapang', 'anyam', 'anyam bambu', 'anyam bambu genggam', 'bambu', 'bambu genggam', 'bambu genggam tang', 'bantu', 'bantu siaga', 'bantu siaga jam', 'duduk', 'duduk alas', 'duduk alas rumput', 'dunia', 'dunia rawan', 'dunia rawan ajar', 'erupsi', 'fokus', 'fokus anyam', 'fokus anyam bambu', 'gelut', 'gelut dunia', 'gelut dunia rawan', 'genggam', 'genggam tang', 'jam', 'juta', 'juta pesona', 'juta pesona sedot', 'kaum', 'kaum perempuan', 'kaum perempuan duduk', 'kelompok', 'kelompok kaum', 'kelompok kaum perempuan', 'komitmen', 'komitmen bantu', 'komitmen bantu siaga', 'koordinasi', 'koordinasi lapor', 'koordinasi lapor posko', 'lapang', 'lapang fokus', 'lapang fokus anyam', 'lapor', 'lapor posko', 'lapor posko rawan', 'lombok', 'lombok milik', 'lombok milik juta', 'masyarakat', 'masyarakat ratap', 'masyarakat ratap erupsi', 'milik', 'milik juta', 'milik juta pesona', 'orang', 'orang wisata', 'perempuan', 'perempuan duduk', 'perempuan duduk alas', 'perempuan gelut', 'perempuan gelut dunia', 'perhati', 'perhati orang', 'perhati orang wisata', 'pesona', 'pesona sedot', 'pesona sedot perhati', 'posko', 'posko rawan', 'posko rawan komitmen', 'ratap', 'ratap erupsi', 'rawan', 'rawan ajar', 'rawan ajar tanggung', 'rawan komitmen', 'rawan komitmen bantu', 'rumput', 'rumput lapang', 'rumput lapang fokus', 'sedot', 'sedot perhati', 'sedot perhati orang', 'siaga', 'siaga jam', 'tang', 'tanggung', 'tanggung orang', 'wisata']

In [43]:
# print idf values
df_idf = pd.DataFrame(tfidf.idf_, index=feature_names,columns=["idf"])
 
# sort ascending
df_idf.sort_values(by=['idf'])

                        idf
rawan              1.693147
perempuan          1.693147
orang              1.693147
ajar               2.098612
perhati            2.098612
...                     ...
gelut dunia rawan  2.098612
gelut dunia        2.098612
gelut              2.098612
tanggung orang     2.098612
wisata             2.098612

[96 rows x 1 columns]

### Step 04 - New sentence TF-IDF transformation

In [44]:
str1 = 'Di kejauhan tampak seorang relawan pria dari Lombok sedang berjalan.'
response = tfidf.transform([str1])

#show result
for col in response.nonzero()[1]:
    print (feature_names[col], ' - ', response[0, col])

rawan  -  0.6279137616509933
lombok  -  0.7782829228046183

In [45]:
print(response[0])

  (0, 79)	0.6279137616509933
  (0, 52)	0.7782829228046183

In [46]:
print (text_preprocessing(str1))

['jauh', 'rawan', 'pria', 'lombok', 'jalan']

<br>
<br>


#### Revision History:
Release: 1.1907.1601
- Initial release

Release: 1.1909.0901
- Install sastrawi package to support Google Colab
- Reorganize code

Release: 1.2011.2701
- Create small sample to make easier to understand

Release: 1.2107.2401
- Tidyup the code